version: '3'

services:
  db:
    image: postgres:14

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: relecloud
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

    ports:
      - 5432:5432

    volumes:
      - postgres-data:/var/lib/postgresql2/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBSERVER_USER} -d ${DBSERVER_DBNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./demo_code/Dockerfile
    network_mode: service:db
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data: